### ISSUE TITLE
FT - Gather actual pollution data

### ISSUE THREAD

**Issue by ivkasiskova** [ERNICommunity/wissifluh17#2]
@HW Team

With the help of the sensor, gather the PM2,5 and PM10 data about the actual pollution at the spot and provide those data for further user representation.

- [ ] #7 Build the sensor
- [ ] #5 Gather the PM2,5 and PM10 data
- [ ] Establish connection to the gateway ( #6 )
